In [2]:
!pip list

Package                Version
---------------------- ---------
backcall               0.1.0
bleach                 2.1.3
certifi                2018.1.18
chardet                3.0.4
colorama               0.3.9
cycler                 0.10.0
decorator              4.3.0
entrypoints            0.2.3
get                    1.0.2
html5lib               1.0.1
httpie                 0.9.9
idna                   2.6
ipykernel              4.8.2
ipython                6.4.0
ipython-genutils       0.2.0
ipywidgets             7.2.1
jedi                   0.12.0
Jinja2                 2.10
jsonschema             2.6.0
jupyter                1.0.0
jupyter-client         5.2.3
jupyter-console        5.2.0
jupyter-core           4.4.0
kiwisolver             1.0.1
MarkupSafe             1.0
matplotlib             2.2.2
mistune                0.8.3
mysql-connector-python 8.0.6
nbconvert              5.3.1
nbformat               4.4.0
notebook               5.5.0
numpy                  1.14.5
pandas                 0.23.1
pandocfilters          1.4.2
parso                  0.2.1
pickleshare            0.7.4
pip                    10.0.1
post                   1.0.1
prompt-toolkit         1.0.15
public                 1.0.1
Pygments               2.2.0
pyparsing              2.2.0
python-dateutil        2.7.3
pytz                   2018.4
pywinpty               0.5.4
pyzmq                  17.0.0
qtconsole              4.3.1
query-string           1.0.1
request                1.0.1
requests               2.18.4
scipy                  1.1.0
seaborn                0.8.1
Send2Trash             1.5.0
setuptools             39.0.1
simplegeneric          0.8.1
six                    1.11.0
terminado              0.8.1
testpath               0.3.1
tornado                5.0.2
traitlets              4.3.2
urllib3                1.22
virtualenv             15.2.0
wcwidth                0.1.7
webencodings           0.5.1
wheel                  0.31.0
widgetsnbextension     3.2.1

In [1]:
!pip list

Package                Version
---------------------- ---------
absl-py                0.2.2
astor                  0.6.2
backcall               0.1.0
bleach                 1.5.0
certifi                2018.1.18
chardet                3.0.4
colorama               0.3.9
cycler                 0.10.0
decorator              4.3.0
entrypoints            0.2.3
forex-python           1.1
gast                   0.2.0
get                    1.0.2
grpcio                 1.12.1
html5lib               0.9999999
httpie                 0.9.9
idna                   2.6
ipykernel              4.8.2
ipython                6.4.0
ipython-genutils       0.2.0
ipywidgets             7.2.1
jedi                   0.12.0
Jinja2                 2.10
jsonschema             2.6.0
jupyter                1.0.0
jupyter-client         5.2.3
jupyter-console        5.2.0
jupyter-core           4.4.0
kiwisolver             1.0.1
Markdown               2.6.11
MarkupSafe             1.0
matplotlib             2.2.2
mistune                0.8.3
mysql-connector-python 8.0.6
nbconvert              5.3.1
nbformat               4.4.0
notebook               5.5.0
numpy                  1.14.5
pandas                 0.23.1
pandocfilters          1.4.2
parso                  0.2.1
pickleshare            0.7.4
pip                    10.0.1
post                   1.0.1
prompt-toolkit         1.0.15
protobuf               3.6.0
public                 1.0.1
Pygments               2.2.0
pyparsing              2.2.0
python-dateutil        2.7.3
pytz                   2018.4
pywinpty               0.5.4
pyzmq                  17.0.0
qtconsole              4.3.1
query-string           1.0.1
request                1.0.1
requests               2.18.4
scipy                  1.1.0
seaborn                0.8.1
Send2Trash             1.5.0
setuptools             39.0.1
simplegeneric          0.8.1
simplejson             3.15.0
six                    1.11.0
tensorboard            1.8.0
tensorflow             1.8.0
termcolor              1.1.0
terminado              0.8.1
testpath               0.3.1
tornado                5.0.2
traitlets              4.3.2
urllib3                1.22
virtualenv             15.2.0
wcwidth                0.1.7
webencodings           0.5.1
Werkzeug               0.14.1
wheel                  0.31.0
widgetsnbextension     3.2.1

In [1]:
import pandas as pd 
df = pd.read_csv('WorldCups.csv')
df.head()

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607

# MISSING VALUE ANALYSIS

# MISSING VALUE FUNCTION

In [ ]:
# Function to calculate missing values by column# Funct 
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [10]:
missing_value = df.isnull().sum()
mis_val_percent = 100 * df.isnull().sum() / len(df)
#print(missing_value)
#print(mis_val_percent)
table = pd.concat([missing_value, mis_val_percent], axis=1) 
New_table = table.rename(columns={0:"Missing value", 1:"% of missing_value"})
print(New_table)

                Missing value  % of missing_value
Year                        0                 0.0
Country                     0                 0.0
Winner                      0                 0.0
Runners-Up                  0                 0.0
Third                       0                 0.0
Fourth                      0                 0.0
GoalsScored                 0                 0.0
QualifiedTeams              0                 0.0
MatchesPlayed               0                 0.0
Attendance                  0                 0.0

In [12]:
df.dtypes.value_counts()

object    6
int64     4
dtype: int64

In [14]:
df.select_dtypes('object')

,Country,Winner,Runners-Up,Third,Fourth,Attendance
0,Uruguay,Uruguay,Argentina,USA,Yugoslavia,590.549
1,Italy,Italy,Czechoslovakia,Germany,Austria,363.000
2,France,Italy,Hungary,Brazil,Sweden,375.700
3,Brazil,Uruguay,Brazil,Sweden,Spain,1.045.246
4,Switzerland,Germany FR,Hungary,Austria,Uruguay,768.607
5,Sweden,Brazil,Sweden,France,Germany FR,819.810
6,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,893.172
7,England,England,Germany FR,Portugal,Soviet Union,1.563.135
8,Mexico,Brazil,Italy,Germany FR,Uruguay,1.603.975
9,Germany,Germany FR,Netherlands,Poland,Brazil,1.865.753
10,Argentina,Argentina,Netherlands,Brazil,Italy,1.545.791
11,Spain,Italy,Germany FR,Poland,France,2.109.723
12,Mexico,Argentina,Germany FR,France,Belgium,2.394.031
13,Italy,Germany FR,Argentina,Italy,England,2.516.215
14,USA,Brazil,Italy,Sweden,Bulgaria,3.587.538
15,France,France,Brazil,Croatia,Netherlands,2.785.100
16,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,2.705.197
17,Germany,Italy,France,Germany,Portugal,3.359.439
18,South Africa,Spain,Netherlands,Germany,Uruguay,3.178.856
19,Brazil,Germany,Argentina,Netherlands,Brazil,3.386.810

# COUNTING UNIQUE ENTRY IN CATEGORICAL VARIABLE

In [13]:
df.select_dtypes('object').apply(pd.Series.nunique, axis = 0)

Country       15
Winner         9
Runners-Up    10
Third         14
Fourth        16
Attendance    20
dtype: int64

# LABEL ENCODING WHEN TWO OR LESS CATEGORY

In [ ]:
from sklearn import  LabelEncoder
# Create a label encoder object
le = LabelEncoder()
le_count = 0

# Iterate through the columns
for col in app_train:
    if app_train[col].dtype == 'object':
        # If 2 or fewer unique categories
        if len(list(app_train[col].unique())) <= 2:
            # Train on the training data
            le.fit(app_train[col])
            # Transform both training and testing data
            app_train[col] = le.transform(app_train[col])
            app_test[col] = le.transform(app_test[col])
            
            # Keep track of how many columns were label encoded
            le_count += 1
            
print('%d columns were label encoded.' % le_count)